### ISSUE TITLE
[DS202] Revise student submissions for Formative 01

### ISSUE THREAD

**Issue by jonjoncardoso** [LSE-DSI/lse-ds202-course-notes#46]

**Comment by jonjoncardoso** [comment]
@mc-o they have until Tuesday to submit. Can you reserve Wednesday morning to mark these formatives? I will share the marking keys with you later via Moodle.


I have office hours on Wed morning but I reserved Wed afternoon for this. So, I can double-mark your corrections later in the day.

**Comment by mc-o** [comment]
@jonjoncardoso yes, of course.  I'll reserve Wednesday morning just for marking. It is great to have the marking keys. Thanks

**Comment by jonjoncardoso** [comment]
There are about 41 submissions already. Direct link [here](https://moodle.lse.ac.uk/mod/coursework/view.php?id=1127006)

**Comment by jonjoncardoso** [comment]
Apparently, it all went to students. It worked!
